--------------------------------------------------------
--  Fichier créé - samedi-juillet-04-2020   
--------------------------------------------------------
DROP TABLE "SYSTEM"."CONSULTATION" cascade constraints;
DROP TABLE "SYSTEM"."DOSSIER_MEDICALE" cascade constraints;
DROP TABLE "SYSTEM"."ORDONNANCE" cascade constraints;
DROP TABLE "SYSTEM"."PATIENT" cascade constraints;
DROP TABLE "SYSTEM"."RDV" cascade constraints;
DROP TABLE "SYSTEM"."STATISTIQUE" cascade constraints;
DROP TABLE "SYSTEM"."STATISTIQUECHRO" cascade constraints;
DROP TABLE "SYSTEM"."STATISTIQUEPA" cascade constraints;
DROP TABLE "SYSTEM"."UTILISATEUR" cascade constraints;
DROP TABLE "SYSTEM"."ANALYSE" cascade constraints;
--------------------------------------------------------
--  DDL for Table CONSULTATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CONSULTATION" 
   (	"NUMCONS" VARCHAR2(30 BYTE), 
	"ID_PATIENT" VARCHAR2(8 BYTE), 
	"OBS" VARCHAR2(1024 BYTE), 
	"MALADIE" VARCHAR2(1204 BYTE), 
	"TRAITMNTPR" VARCHAR2(1204 BYTE), 
	"DATE_RDV" DATE, 
	"HEURE" VARCHAR2(10 BYTE), 
	"MONTANTP" VARCHAR2(20 BYTE), 
	"MALADIE_CHRONIQUE" VARCHAR2(1204 BYTE), 
	"DOSE" VARCHAR2(1204 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DOSSIER_MEDICALE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DOSSIER_MEDICALE" 
   (	"NUMCONS" VARCHAR2(30 BYTE), 
	"ID_PATIENT" VARCHAR2(8 BYTE), 
	"GROUPE_SANGUIN" VARCHAR2(10 BYTE), 
	"POID" VARCHAR2(10 BYTE), 
	"TAILLE" VARCHAR2(10 BYTE), 
	"INFORMATION_DE_MALADIE_CHRO" VARCHAR2(2048 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDONNANCE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ORDONNANCE" 
   (	"ID_PATIENT" VARCHAR2(8 BYTE), 
	"NUMCONS" VARCHAR2(30 BYTE), 
	"ODR" VARCHAR2(4000 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PATIENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PATIENT" 
   (	"ID_PATIENT" VARCHAR2(8 BYTE), 
	"NOM" VARCHAR2(25 BYTE), 
	"PRENOM" VARCHAR2(25 BYTE), 
	"SEXE" VARCHAR2(20 BYTE), 
	"DATE_DE_NAISSANCE" DATE, 
	"ADRESSE" VARCHAR2(30 BYTE), 
	"TELEPHONE" VARCHAR2(10 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE), 
	"DATEDINSCRIPTION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RDV
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."RDV" 
   (	"DATE_RDV" DATE, 
	"HEURE" VARCHAR2(10 BYTE), 
	"NOM" VARCHAR2(30 BYTE), 
	"PRENOM" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(60 BYTE), 
	"TEL" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STATISTIQUE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STATISTIQUE" 
   (	"ID_PATIENT" VARCHAR2(8 BYTE), 
	"MALADIE" VARCHAR2(30 BYTE), 
	"DATE_RDV" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STATISTIQUECHRO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STATISTIQUECHRO" 
   (	"ID_PATIENT" VARCHAR2(8 BYTE), 
	"MALADIE_CHRONIQUE" VARCHAR2(30 BYTE), 
	"DATE_RDV" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STATISTIQUEPA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."STATISTIQUEPA" 
   (	"ID_PATIENT" VARCHAR2(8 BYTE), 
	"DATE_RDV" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UTILISATEUR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UTILISATEUR" 
   (	"USERNAME" VARCHAR2(40 BYTE), 
	"PASSWORDS" VARCHAR2(60 BYTE), 
	"SPE" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ANALYSE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ANALYSE" 
   (	"NUMCONS" VARCHAR2(30 BYTE), 
	"ID_PATIENT" VARCHAR2(8 BYTE), 
	"ANALYSE_DEMANDER" VARCHAR2(2048 BYTE), 
	"LEUR_RESULTAT" VARCHAR2(2024 BYTE), 
	"COMMENTAIRE" VARCHAR2(2050 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CONSULTATION
SET DEFINE OFF;
Insert into SYSTEM.CONSULTATION (NUMCONS,ID_PATIENT,OBS,MALADIE,TRAITMNTPR,DATE_RDV,HEURE,MONTANTP,MALADIE_CHRONIQUE,DOSE) values ('0407201','00000001','cbv','grippe','panadole',to_date('05/05/15','DD/MM/RR'),'16H40','1000Da','diabete','1000g par jour');
Insert into SYSTEM.CONSULTATION (NUMCONS,ID_PATIENT,OBS,MALADIE,TRAITMNTPR,DATE_RDV,HEURE,MONTANTP,MALADIE_CHRONIQUE,DOSE) values ('0407202','00000002','cbv','grippe','panadole',to_date('05/05/14','DD/MM/RR'),'16H40','1000Da','diabete','1000g par jour');
REM INSERTING into SYSTEM.DOSSIER_MEDICALE
SET DEFINE OFF;
Insert into SYSTEM.DOSSIER_MEDICALE (NUMCONS,ID_PATIENT,GROUPE_SANGUIN,POID,TAILLE,INFORMATION_DE_MALADIE_CHRO) values ('0407201','00000001','test','test','test','test');
REM INSERTING into SYSTEM.ORDONNANCE
SET DEFINE OFF;
REM INSERTING into SYSTEM.PATIENT
SET DEFINE OFF;
Insert into SYSTEM.PATIENT (ID_PATIENT,NOM,PRENOM,SEXE,DATE_DE_NAISSANCE,ADRESSE,TELEPHONE,EMAIL,DATEDINSCRIPTION) values ('00000001','test','test','Homme',to_date('05/05/01','DD/MM/RR'),'test','test','test',to_date('05/05/15','DD/MM/RR'));
Insert into SYSTEM.PATIENT (ID_PATIENT,NOM,PRENOM,SEXE,DATE_DE_NAISSANCE,ADRESSE,TELEPHONE,EMAIL,DATEDINSCRIPTION) values ('00000002','test2','test2','Femme',to_date('05/05/01','DD/MM/RR'),'test','test','test',to_date('05/05/15','DD/MM/RR'));
REM INSERTING into SYSTEM.RDV
SET DEFINE OFF;
Insert into SYSTEM.RDV (DATE_RDV,HEURE,NOM,PRENOM,EMAIL,TEL) values (to_date('05/05/15','DD/MM/RR'),'16H40','test (X)','test (X)','test','test');
Insert into SYSTEM.RDV (DATE_RDV,HEURE,NOM,PRENOM,EMAIL,TEL) values (to_date('05/05/14','DD/MM/RR'),'16H40','test2 (X)','test2 (X)','test','test');
Insert into SYSTEM.RDV (DATE_RDV,HEURE,NOM,PRENOM,EMAIL,TEL) values (to_date('06/06/15','DD/MM/RR'),'15H00','test (V)','test (V)','test','test');
Insert into SYSTEM.RDV (DATE_RDV,HEURE,NOM,PRENOM,EMAIL,TEL) values (to_date('01/02/15','DD/MM/RR'),'17H40','test (V)','test (V)','test','test');
Insert into SYSTEM.RDV (DATE_RDV,HEURE,NOM,PRENOM,EMAIL,TEL) values (to_date('05/05/15','DD/MM/RR'),'17H40','test (X)','test (X)','test','test');
REM INSERTING into SYSTEM.STATISTIQUE
SET DEFINE OFF;
Insert into SYSTEM.STATISTIQUE (ID_PATIENT,MALADIE,DATE_RDV) values ('00000003','fievre',to_date('06/06/15','DD/MM/RR'));
Insert into SYSTEM.STATISTIQUE (ID_PATIENT,MALADIE,DATE_RDV) values ('00000001','grippe',to_date('05/05/15','DD/MM/RR'));
Insert into SYSTEM.STATISTIQUE (ID_PATIENT,MALADIE,DATE_RDV) values ('00000002','grippe',to_date('05/05/14','DD/MM/RR'));
REM INSERTING into SYSTEM.STATISTIQUECHRO
SET DEFINE OFF;
Insert into SYSTEM.STATISTIQUECHRO (ID_PATIENT,MALADIE_CHRONIQUE,DATE_RDV) values ('00000001','diabete',to_date('05/05/15','DD/MM/RR'));
Insert into SYSTEM.STATISTIQUECHRO (ID_PATIENT,MALADIE_CHRONIQUE,DATE_RDV) values ('00000002','diabete',to_date('05/05/14','DD/MM/RR'));
Insert into SYSTEM.STATISTIQUECHRO (ID_PATIENT,MALADIE_CHRONIQUE,DATE_RDV) values ('00000003','diabete',to_date('06/06/15','DD/MM/RR'));
REM INSERTING into SYSTEM.STATISTIQUEPA
SET DEFINE OFF;
Insert into SYSTEM.STATISTIQUEPA (ID_PATIENT,DATE_RDV) values ('00000003',to_date('06/06/15','DD/MM/RR'));
Insert into SYSTEM.STATISTIQUEPA (ID_PATIENT,DATE_RDV) values ('00000001',to_date('05/05/15','DD/MM/RR'));
Insert into SYSTEM.STATISTIQUEPA (ID_PATIENT,DATE_RDV) values ('00000002',to_date('05/05/14','DD/MM/RR'));
REM INSERTING into SYSTEM.UTILISATEUR
SET DEFINE OFF;
Insert into SYSTEM.UTILISATEUR (USERNAME,PASSWORDS,SPE) values ('khicha ines','12001','Medecin');
Insert into SYSTEM.UTILISATEUR (USERNAME,PASSWORDS,SPE) values ('kaddour hadjer','32001','Medecin');
Insert into SYSTEM.UTILISATEUR (USERNAME,PASSWORDS,SPE) values ('test','2001','Secretaire');
REM INSERTING into SYSTEM.ANALYSE
SET DEFINE OFF;
Insert into SYSTEM.ANALYSE (NUMCONS,ID_PATIENT,ANALYSE_DEMANDER,LEUR_RESULTAT,COMMENTAIRE) values ('0407201','00000001','test','positifs ','test');
--------------------------------------------------------
--  DDL for Index SYS_C0011281
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C0011281" ON "SYSTEM"."CONSULTATION" ("NUMCONS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012084
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C0012084" ON "SYSTEM"."DOSSIER_MEDICALE" ("NUMCONS", "ID_PATIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ORDONNANCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ORDONNANCE_PK" ON "SYSTEM"."ORDONNANCE" ("NUMCONS", "ID_PATIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011275
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C0011275" ON "SYSTEM"."PATIENT" ("ID_PATIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011276
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C0011276" ON "SYSTEM"."RDV" ("DATE_RDV", "HEURE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012016
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C0012016" ON "SYSTEM"."STATISTIQUE" ("ID_PATIENT", "MALADIE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012018
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C0012018" ON "SYSTEM"."STATISTIQUECHRO" ("ID_PATIENT", "MALADIE_CHRONIQUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012052
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C0012052" ON "SYSTEM"."STATISTIQUEPA" ("ID_PATIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0012090
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C0012090" ON "SYSTEM"."ANALYSE" ("NUMCONS", "ID_PATIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CONSULTATION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SYSTEM"."CONSULTATION_TRG" 
BEFORE INSERT ON CONSULTATION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."CONSULTATION_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table CONSULTATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CONSULTATION" ADD CONSTRAINT "SYS_C0011281" PRIMARY KEY ("NUMCONS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOSSIER_MEDICALE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DOSSIER_MEDICALE" ADD PRIMARY KEY ("NUMCONS", "ID_PATIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDONNANCE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ORDONNANCE" ADD CONSTRAINT "ORDONNANCE_PK" PRIMARY KEY ("NUMCONS", "ID_PATIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."ORDONNANCE" MODIFY ("ID_PATIENT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."ORDONNANCE" MODIFY ("NUMCONS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PATIENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PATIENT" ADD PRIMARY KEY ("ID_PATIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."PATIENT" MODIFY ("DATEDINSCRIPTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RDV
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."RDV" ADD PRIMARY KEY ("DATE_RDV", "HEURE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."RDV" MODIFY ("NOM" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."RDV" MODIFY ("PRENOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STATISTIQUE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STATISTIQUE" ADD CONSTRAINT "SYS_C0012016" PRIMARY KEY ("ID_PATIENT", "MALADIE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATISTIQUECHRO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STATISTIQUECHRO" ADD PRIMARY KEY ("ID_PATIENT", "MALADIE_CHRONIQUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATISTIQUEPA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."STATISTIQUEPA" ADD PRIMARY KEY ("ID_PATIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UTILISATEUR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."UTILISATEUR" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."UTILISATEUR" MODIFY ("PASSWORDS" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."UTILISATEUR" MODIFY ("SPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANALYSE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ANALYSE" ADD PRIMARY KEY ("NUMCONS", "ID_PATIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONSULTATION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CONSULTATION" ADD FOREIGN KEY ("DATE_RDV", "HEURE")
	  REFERENCES "SYSTEM"."RDV" ("DATE_RDV", "HEURE") ENABLE;
 
  ALTER TABLE "SYSTEM"."CONSULTATION" ADD FOREIGN KEY ("ID_PATIENT")
	  REFERENCES "SYSTEM"."PATIENT" ("ID_PATIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOSSIER_MEDICALE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DOSSIER_MEDICALE" ADD FOREIGN KEY ("NUMCONS")
	  REFERENCES "SYSTEM"."CONSULTATION" ("NUMCONS") ENABLE;
 
  ALTER TABLE "SYSTEM"."DOSSIER_MEDICALE" ADD FOREIGN KEY ("ID_PATIENT")
	  REFERENCES "SYSTEM"."PATIENT" ("ID_PATIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDONNANCE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ORDONNANCE" ADD FOREIGN KEY ("ID_PATIENT")
	  REFERENCES "SYSTEM"."PATIENT" ("ID_PATIENT") ENABLE;
 
  ALTER TABLE "SYSTEM"."ORDONNANCE" ADD FOREIGN KEY ("NUMCONS")
	  REFERENCES "SYSTEM"."CONSULTATION" ("NUMCONS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ANALYSE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ANALYSE" ADD FOREIGN KEY ("NUMCONS")
	  REFERENCES "SYSTEM"."CONSULTATION" ("NUMCONS") ENABLE;
 
  ALTER TABLE "SYSTEM"."ANALYSE" ADD FOREIGN KEY ("ID_PATIENT")
	  REFERENCES "SYSTEM"."PATIENT" ("ID_PATIENT") ENABLE;
